# Generated by Django 4.1.2 on 2024-03-29 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favourite_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritecategory',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='favouritetag',
            unique_together={('user', 'name')},
        ),
    ]
